collaborators/luis_bravo.md
Markdown file`luis_bravo.md` was added inside _/collaborators_ folder where information about me (Luis Bravo) is described.
=> Added a markdown with Luis Bravo's bio info

collaborators/carlos_chihenseck.md
primer commit con mi markdown file
=> mi primer commit con mi markdown file

collaborators/josejuan_diazcampos.md
=> mi pull request del markdown

collaborators/axel_escoto_garcia.md
Add my MD file into the collaborator's folder.
=> collab: add Axel bio

collaborators/jaime_galindo.md
Primer pull request con mi archivo .md de presentación
=> Mi archivo de presentación

collaborators/axel_gallardo.md
Agregado documento de colaborador de Axel Gallardo
=> Bio Axel Gallardo

collaborators/antoniahoerburger.md
Este es mi primer pull request
=> Primer Pull Request Antonia

collaborators/santiago_mdeo.md
should be pretty simple pull request
=> Added markdown file with my name

collaborators/valeria_oliva.md
Archivo Bio Valeria Oliva Lab00
=> Archivo Bio Valeria Oliva

collaborators/luis_regalado.md
Changes to be committed:
new file:   collaborators/luis_regalado.md
with my name as contents
=> creacion branch Regalado Floriano

collaborators/luis_santana.md
archivo para introducirme con el salon
=> archivo introductorio de Luis Angel Santana

collaborators/sergio_villa.md
=> Agregando markdown de Sergio Villa

spark/notebooks/labs/lab01/lab01_my_name - copia.ipynb
laboratorio 1 con jupyternotebook
=> Carloschihenseck lab01

spark/notebooks/labs/lab01/lab01_Axel-Fernandez.ipynb
Data manipulation to get which is the most popular songs and clasify which songs where listened by each one of the users.
=> Song Data Manipulation

spark/notebooks/labs/lab01/lab01_Jaime_Galindo.ipynb
Archivo lab01_Jaime_Galindo.ipynb con pasos del laboratorio creado en directorio \spark\notebooks\labs\lab01
=> Lab01: Playlisy analyzer terminado

spark/notebooks/labs/lab01/lab01_RegaladoFloriano.ipynb
spotifake music idea with sets
new file:   notebooks/labs/lab01/lab01_RegaladoFloriano.ipynb
=> Lab01 Regalado Floriano

spark/notebooks/labs/lab01/lab01_sebastian_serrano.ipynb
=> Sebastian_Serrano_lab01

spark/notebooks/labs/lab01/lab01_bernardoorozco.ipynb
=> lab01 Bernardo Orozco

spark/notebooks/labs/lab02/lab02_luis_bravo.ipynb, spark/notebooks/lib/luisbravor00/bank_account_manager.py
Added the Lab002 code adding my Class and Lab jupyter file.
=> Lab02: Bank Account Manager (Luis Bravo's version)

spark/notebooks/labs/lab02/lab02_jaime_galindo.ipynb, spark/notebooks/lib/jaime_galindo/BankAccount.py
Archivo de BankAccount.py con clase BankAccount y notebook para probar la clase usando process
=> Lab02 Bank account manager

spark/notebooks/labs/lab02/lab02_Regalado_Floriano.ipynb, spark/notebooks/lib/regalado_floriano/BankAccount.py
Modulo con Bank Account y ejemplo en las diapositivas
=> Lab02 regalado floriano Bank account

spark/notebooks/labs/lab01/lab01_axel_eg.ipynb
=> labs: add lab 1

spark/notebooks/examples/luis_bravo_gen_schema.ipynb, spark/notebooks/lib/luisbravor00/spark_utils.py
Added the code to create schemas dinamically.
=> Creating Dinamically Schemas (Luis Bravo's version)

spark/notebooks/examples/axelgallardo_gen_schema.ipynb, spark/notebooks/lib/axelgallardo/spark_utils.py
axelgallardo_gen_schema implementation
=> axelgallardo_gen_schema

spark/.gitignore, spark/notebooks/examples/lecture_09_data_sources.ipynb, spark/notebooks/labs/lab03/lab03_template.ipynb
new file:   .gitignore
new file:   notebooks/examples/lecture_09_data_sources.ipynb
new file:   notebooks/labs/lab03/lab03_template.ipynb
=> Changes to be committed:

spark/notebooks/examples/axel_fernandez_schema.ipynb, spark/notebooks/lib/axel_fernandez/spark_utils.py
late delivering of generate schema. axel lib
=> generate schema

spark/notebooks/labs/lab06/lab06_axel_eg.ipynb
Add the lab 6: Writing data in Neo4j.
=> labs: add lab 6

spark/notebooks/labs/lab06/lab06_JaimeGalindo.ipynb
Laboratorio terminado con información de dataframes enviadas a Neo4j y recuperadas las relaciones, fue necesario hacer indices en Neo4j para publicarlos porque sino se tardaba demaciado tiempo haciendo comparaciones para verificar que no existan los nodos previamente.
=> Jaime galindo lab06

spark/notebooks/labs/lab06/lab06_regalado_floriano.ipynb
Finished the lab, changes to spark utils will come in the next "release"
=> 	new file:   notebooks/labs/lab06/lab06_regalado_floriano.ipynb
